Fix register
dger804/InkCentral pull request #3
Opened 2020-11-12 23:53 UTC by omontoy

Se implementa la funcionalidad de Log in
Se valida email y contraseña

2020-11-13 16:16 UTC, simonhoyos requested changes

2020-11-13 16:16 UTC, simonhoyos commented on src/components/Home.js
> +	state = {
Ojo con la consistencia en la identación. En algunos lugares la identación está a 2 espacios y en otros a 1 tab. Se puede usar el que sea mientras sea consistente

2020-11-14 17:24 UTC, GiovannyRamirez commented on src/components/Home.js
> +	state = {
Ya revisé la identación en todos los archivos, quedando en 2 espacios.
Añadí más datos mockeados y se probaron dichos usuarios dentro del Login.

2020-11-14 17:58 UTC, simonhoyos approved these changes

2020-11-14 17:58 UTC, simonhoyos commented on src/components/Home.js
> +	state = {
Super

2020-11-14 19:23 UTC, merged