Logout state behavior
dger804/InkCentral pull request #38
Opened 2020-12-15 16:30 UTC by omontoy

- Reset user login and register to the initial state
- Remove dispatch from useEffect
- Indent code
- Remove error_artist as argument of useEffect
- Add one link to update artist or client user form

![image](https://user-images.githubusercontent.com/20135083/102243071-c25a2100-3ec8-11eb-9a58-9b67b97e6918.png)

2020-12-15 19:00 UTC, simonhoyos requested changes

2020-12-15 19:00 UTC, simonhoyos commented on src/components/Navigation.js
> +  let user = null
El tipo de usuario puede ser un estado, ya sea un estado del componente o un estado en redux

2020-12-15 21:55 UTC, IvanG1981 approved these changes

2020-12-16 14:42 UTC, simonhoyos approved these changes

2020-12-16 14:51 UTC, merged