Styles
dger804/InkCentral pull request #5
Opened 2020-11-16 23:00 UTC by IvanG1981

- React-Bootstrap installation 

- Bootstrap implementation in Login

![image](https://user-images.githubusercontent.com/35941662/99318293-6c487e00-2835-11eb-9433-ae2c7ea5cfe5.png)

2020-11-16 23:06 UTC, simonhoyos requested changes

2020-11-16 23:06 UTC, simonhoyos commented on src/components/Login.js
> +// import { Link } from 'react-router-dom'
Si no se va a usar mejor borrarlo y no dejar comentarios

2020-11-16 23:06 UTC, simonhoyos commented on src/components/Login.js
> +		password: "",
Ojo con la identación, en este archivo está a 4 espacios y en el resto a 2 espacios. Lo ideal es ser consistente

2020-11-16 23:06 UTC, simonhoyos commented on src/components/Login.js
> +              <Form.Control type="email"
Te recomiendo pasar `type` a la siguiente linea así no tienes que poner todos los props con una identación adicional

2020-11-16 23:06 UTC, simonhoyos commented on src/components/Login.js
> +              <Form.Control type="password"
lo mismo que el comentario anterior

2020-11-16 23:06 UTC, simonhoyos commented on src/App.css
> +.jumbotron{
Cuando vamos a modificar los estilos que tiene una librería es recomendable no usar las clases que ya tiene definidas la librería. Yo le agregaría una clase extra al componente y usaría esa clase para agregar los estilos.

2020-11-16 23:06 UTC, simonhoyos commented on src/App.css
> +  background-color: darkgrey !important;
Busca otras alternativas que no requiran el uso de !important, el uso de !important debería ser limitado a algunos casos super especiales. En general no se recomienda su uso

2020-11-17 01:00 UTC, GiovannyRamirez commented on src/components/Login.js
> +		password: "",
La identación se ve bien en mi editor de texto VSCode.

2020-11-17 01:05 UTC, GiovannyRamirez commented on src/App.css
> +  background-color: darkgrey !important;
lo revisaremos, sin embargo, si se adicionó una clase dentro del componente

2020-11-17 15:15 UTC, simonhoyos reviewed
Último arreglo y queda listo

2020-11-17 15:15 UTC, simonhoyos commented on src/App.css
> +  background-color: darkgrey !important;
prueba con el selector `.background.background` si te funciona ya sería el último cambio. Si no funciona por ahora lo subimos así con el important

2020-11-17 19:22 UTC, simonhoyos approved these changes

2020-11-17 19:31 UTC, merged